### ISSUE TITLE
Does it  still work with vim8 and git 2?

### ISSUE THREAD

**Issue by alex-shamshurin** [jasoncodes/ctrlp-modified.vim#4]
CtrlPModified shows `NO ENTRIES`. CtrlPBranch shows `fatal: Not a valid object name origin/HEAD`. What is it?

**Comment by lugray** [comment]
When CtrlPModified shows NO ENTRIES, it means you have no uncommitted changes.

**Comment by jasoncodes** [comment]
Hi Alex. Apologies for the delayed reply. I somehow missed the original notification of this issue.

Yes, `ctrlp-modified.vim` works well with Vim 8 and git 2. The error you encountered with `CtrlPBranch` is due to `origin/HEAD` not always being set. @lugray has written a fix for this and it’s 
now merged. Update your plugin install to the latest and it should all work now. Thanks @lugray!
